name: neocortexapp
description: NeoCortex App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
#AIzaSyD1uy6ktSRcV_FrSX6f7A4eVkStxEA1NyY
version: 2.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  smooth_page_indicator: ^1.1.0
  video_player: ^2.5.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  package_info_plus: ^4.2.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  jwt_decoder: ^2.0.1
  convex_bottom_bar: ^3.2.0
  turkish: ^0.2.1
  geocoding: ^2.1.1
  percent_indicator: ^4.0.1
  map_launcher: ^2.5.0
  flutter_svg:
  cached_network_image: ^3.3.0
  camera: ^0.10.5+5
  fluttertoast: ^8.2.2
  native_exif: ^0.5.0
  sensors_plus: ^4.0.1
  sqflite: ^2.2.8+1
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.3.0
  contained_tab_bar_view: ^0.8.0
  need_resume: ^1.0.7+1
  http_parser: ^4.0.2
  native_shutter_sound: ^0.0.1
  crop_your_image: ^0.7.5
  ffi: ^2.0.1
  image: ^4.0.15
  quiver: ^3.0.0
  easy_image_viewer: ^1.2.1
  path: ^1.8.3
  webview_flutter: ^4.4.2
  flutter_pdfview: ^1.3.2
  stop_watch_timer: ^3.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logoSmall.png
    - assets/images/logo.png
    - assets/images/bottomlogo.png
    - assets/images/map1.png
    - assets/images/map2.png
    - assets/images/map3.png
    - assets/images/map4.png
    - assets/images/map5.png
    - assets/images/map6.png
    - assets/images/map7.png
    - assets/images/map1mavi.png
    - assets/images/map1mor.png
    - assets/images/map1ok.png
    - assets/images/map2mavi.png
    - assets/images/map2mor.png
    - assets/images/map2ok.png
    - assets/images/eco_miniok.png
    - assets/images/eco_mini.png
    - assets/images/map4ok.png
    - assets/images/carrefour.png
    - assets/images/map5ok.png
    - assets/images/migros.png
    - assets/images/map6ok.png
    - assets/images/macrocenter.png
    - assets/images/map7ok.png
    - assets/images/diger.png
    - assets/images/vector.png
    - assets/images/gyro.png
    - assets/videos/onboard-0.mp4
    - assets/videos/onboard-1.mp4
    - assets/videos/onboard-2.mp4
    - assets/animations/location.json
    - assets/animations/loading.json
    - assets/pdf/uygulama_turu.pdf
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
